curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 0.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 1.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 2.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 3.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 4.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 5.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 6.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 7.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 8.jpg &
curl --proxy localhost:8888 http://foo.prinmath.com/images/wine3.jpg > 9.jpg &
